# Generated by Django 5.0.7 on 2024-08-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='published_user',
        ),
    ]
